#!/usr/bin/env bash
set -eu

ROOT_DIR=$(
  cd "$(dirname "$0")"
  pwd
)

source "$ROOT_DIR/utils/source.sh"
source_modules \
  utils/output.sh \
  utils/path.sh \
  utils/validate.sh \
  profiles/common.sh

main() {
  path_prepare
  validate_require_arg_count "$#" 1 "<name>"
  validate_names "$1"
  if profile_exists "$1"; then
    output_die "profile already exists: $1"
  fi
  profile_create "$1"
  output_log "profile added: $1"
}

main "$@"
