#!/usr/bin/env bash
set -eu

ROOT_DIR=$(
  cd "$(dirname "$0")"
  pwd
)

source "$ROOT_DIR/utils/source.sh"
source_modules \
  utils/output.sh \
  utils/path.sh \
  utils/validate.sh \
  profiles/common.sh \
  hosts/common.sh

main() {
  path_prepare
  validate_require_arg_count "$#" 2 "<profile> <alias>"
  validate_names "$1" "$2"
  profile_require "$1"
  host_require "$1" "$2"
  host_remove "$1" "$2"
  output_log "host removed: $2"
}

main "$@"
