#!/usr/bin/env bash
set -eu

ROOT_DIR=$(
  cd "$(dirname "$0")"
  pwd
)

source "$ROOT_DIR/utils/source.sh"
source_modules \
  utils/output.sh \
  utils/path.sh \
  utils/table.sh \
  utils/validate.sh \
  profiles/common.sh \
  hosts/common.sh

main() {
  local profile
  path_prepare
  validate_require_arg_max "$#" 1 "[profile]"
  if [ "$#" -eq 1 ]; then
    profile=$1
  else
    profile=$(profile_current_or_die)
  fi
  profile_require "$profile"
  table_reset
  table_set_headers alias user hostname
  host_each "$profile" table_add_row
  table_print
}

main "$@"
