#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"

source_modules() {
  local module
  for module in "$@"; do
    # shellcheck source=/dev/null
    source "$ROOT_DIR/$module"
  done
}

[[ -f "$ROOT_DIR/abstracts/$OS.sh" ]] || exit 1
source_modules \
  abstracts/$OS.sh \
  utils/network.sh \
  utils/pair.sh \
  utils/table.sh

main() {
  network_prepare_context
  network_local
  network_neighbors
}

main "$@"
