#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"

source "$ROOT_DIR/utils/source.sh"
source_modules \
  utils/path.sh \
  utils/pair.sh \
  profiles/common.sh

main() {
  local current
  path_prepare
  pair_reset
  pair_set_title current
  if current=$(profile_current); then
    pair_add profile "$current"
    pair_add path "$(profile_dir "$current")"
  else
    pair_add profile "(none)"
  fi
  pair_print
}

main "$@"
