#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"

# shellcheck source=/dev/null
source "$ROOT_DIR/../utils/source.sh"
[[ -f "$ROOT_DIR/../utils/abstracts/$OS.sh" ]] || exit 1
source_modules \
  ../utils/abstracts/$OS.sh \
  ../utils/filesystem.sh \
  ../utils/network.sh \
  ../utils/pair.sh \
  ../utils/ssh.sh \
  ../utils/table.sh

main() {
  local neighbors
  if [[ $# -eq 0 ]]; then
    network_local
    return 0
  fi
  neighbors="$(network_neighbors_records "$@")"
  filesystem_prepare
  filesystem_sync "$neighbors"
  network_neighbors_print "$neighbors"
}

main "$@"
