#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() {
  echo "$0 <alias> <user> <hostname>" >&2
  exit 1
}

# shellcheck source=/dev/null
source "$ROOT_DIR/../utils/source.sh"
source_modules \
  ../utils/host.sh \
  ../utils/profile.sh \
  ../utils/ssh.sh \
  ../utils/validate.sh

main() {
  local profile
  local fingerprint
  [ "$#" -eq 3 ] || usage
  validate_names "$1" "$2"
  profile_prepare
  profile=$(profile_default)
  if host_exists "$profile" "$1"; then
    exit 1
  fi
  fingerprint=$(host_prepare_connection "$profile" "$1" "$3")
  host_add "$profile" "$1" "$2" "$3" "$fingerprint"
  exec "$ROOT_DIR/status"
}

main "$@"
