#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() {
  echo "$0 <alias>" >&2
  exit 1
}

# shellcheck source=/dev/null
source "$ROOT_DIR/../utils/source.sh"
source_modules \
  ../utils/host.sh \
  ../utils/profile.sh \
  ../utils/ssh.sh \
  ../utils/validate.sh

main() {
  local profile
  [ "$#" -eq 1 ] || usage
  validate_names "$1"
  profile_prepare
  profile=$(profile_default)
  if ! host_exists "$profile" "$1"; then
    exit 1
  fi
  host_remove "$profile" "$1"
  exec "$ROOT_DIR/status"
}

main "$@"
