#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() {
  echo "$0 <name>" >&2
  exit 1
}

# shellcheck source=/dev/null
source "$ROOT_DIR/../utils/source.sh"
source_modules \
  ../utils/path.sh \
  ../utils/profile.sh \
  ../utils/validate.sh

main() {
  path_prepare
  validate_require_arg_count "$#" 1 || usage
  validate_names "$1"
  if ! profile_exists "$1"; then
    exit 1
  fi
  profile_clear_current_if_selected "$1"
  profile_remove "$1"
  exec "$ROOT_DIR/status"
}

main "$@"
