#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() {
  echo "$0 <alias> [ssh args...]" >&2
  exit 1
}

# shellcheck source=/dev/null
source "$ROOT_DIR/../utils/source.sh"
source_modules \
  ../utils/host.sh \
  ../utils/profile.sh \
  ../utils/ssh.sh

main() {
  local alias
  local profile
  [ "$#" -ge 1 ] || usage
  alias=$1
  shift
  profile_prepare
  profile=$(profile_default)
  if ! host_exists "$profile" "$alias"; then
    return 1
  fi
  host_write_ssh_config "$profile" "$MANTRA_GENERATED_CONFIG_FILE"
  exec ssh -F "$MANTRA_GENERATED_CONFIG_FILE" "$alias" "$@"
}

main "$@"
