path_prepare() {
  MANTRA_HOME=${MANTRA_HOME:-"$HOME/.config/mantra"}
  MANTRA_PROFILES_DIR=$MANTRA_HOME/profiles
  MANTRA_STATE_DIR=$MANTRA_HOME/state
  MANTRA_CURRENT_PROFILE_FILE=$MANTRA_STATE_DIR/current_profile
  MANTRA_GENERATED_CONFIG_FILE=$MANTRA_STATE_DIR/ssh_config
  mkdir -p "$MANTRA_PROFILES_DIR" "$MANTRA_STATE_DIR"
}
