profile_prepare() {
  MANTRA_HOME=${MANTRA_HOME:-"$HOME/.config/mantra"}
  MANTRA_PROFILES_DIR=$MANTRA_HOME/profiles
  MANTRA_STATE_DIR=$MANTRA_HOME/state
  MANTRA_GENERATED_CONFIG_FILE=$MANTRA_STATE_DIR/ssh_config
  MANTRA_HOSTS_FILE=$MANTRA_PROFILES_DIR/default/hosts
  MANTRA_KNOWN_HOSTS_FILE=$MANTRA_PROFILES_DIR/default/known_hosts
  mkdir -p "$MANTRA_PROFILES_DIR" "$MANTRA_STATE_DIR"
  mkdir -p "$MANTRA_PROFILES_DIR/default"
  [ -f "$MANTRA_HOSTS_FILE" ] || : >"$MANTRA_HOSTS_FILE"
  [ -f "$MANTRA_KNOWN_HOSTS_FILE" ] || : >"$MANTRA_KNOWN_HOSTS_FILE"
}
